# -*- coding: utf-8 -*-
"""HAYAT-ESSALHI-iss.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/120_zV5newn8MhrM6aypQJAy5cMueo6gB
"""

pip install ucimlrepo

from ucimlrepo import fetch_ucirepo

# fetch dataset
heart_disease = fetch_ucirepo(id=45)

# data (as pandas dataframes)
X = heart_disease.data.features
y = heart_disease.data.targets

# metadata
print(heart_disease.metadata)

# variable information
print(heart_disease.variables)

"""# Task
Analyze the heart disease dataset (id=45) by fetching it, exploring its structure (head, info, describe, value_counts), generating histograms for all numerical features, creating a bar plot for the target variable, and generating a correlation heatmap of the numerical features and the target, then summarize the key insights from the visualizations.

## Re-fetch Heart Disease Data

### Subtask:
Fetch the heart disease dataset (id=45) using `ucimlrepo` again to ensure the data is loaded into `X` (features) and `y` (targets) DataFrames. This step will address the previous `ModuleNotFoundError`.

**Reasoning**:
The previous attempt to fetch the dataset failed due to a ModuleNotFoundError. I will re-attempt to import `fetch_ucirepo`, fetch the heart disease dataset (id=45), and assign the features to `X` and targets to `y` to ensure the data is correctly loaded.
"""

from ucimlrepo import fetch_ucirepo

# fetch dataset
heart_disease = fetch_ucirepo(id=45)

# data (as pandas dataframes)
X = heart_disease.data.features
y = heart_disease.data.targets

# metadata
print(heart_disease.metadata)

# variable information
print(heart_disease.variables)

"""## Explore Data Structure

### Subtask:
Display basic information about the loaded dataframes `X` and `y`, such as their `.head()`, `.info()`, `.describe()` for numerical features, and `.value_counts()` for the target variable `y`.

**Reasoning**:
To explore the dataframes `X` and `y` as requested, I will use `.head()`, `.info()`, and `.describe()` for both, and `.value_counts()` for `y` to display their basic structure and statistical summaries.
"""

print("X - First 5 rows:")
print(X.head())
print("\nX - Info:")
X.info()
print("\nX - Descriptive Statistics:")
print(X.describe())

print("\n\ny - First 5 rows:")
print(y.head())
print("\ny - Info:")
y.info()
print("\ny - Descriptive Statistics:")
print(y.describe())
print("\ny - Value Counts:")
print(y.value_counts())

"""## Generate Histograms for Features

### Subtask:
Create histograms for all numerical features in the `X` DataFrame to visualize the distribution of each characteristic of the patients.

**Reasoning**:
To visualize the distribution of numerical features, I will import `matplotlib.pyplot` and `seaborn`, identify numerical columns in the `X` DataFrame, and then iterate through them to generate and display a histogram for each.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Identify numerical columns in X
numerical_cols = X.select_dtypes(include=['int64', 'float64']).columns

# Create histograms for each numerical feature
plt.figure(figsize=(15, 10))
for i, col in enumerate(numerical_cols):
    plt.subplot(3, 5, i + 1) # Adjust subplot grid based on number of features
    sns.histplot(X[col].dropna(), kde=True)
    plt.title(f'Distribution of {col}')
    plt.xlabel(col)
    plt.ylabel('Frequency')

plt.tight_layout()
plt.show()

"""## Generate Bar Plot for Target

### Subtask:
Create a bar plot or count plot for the `y` target variable to show the distribution of the heart disease outcomes. Ensure the plot has appropriate labels and a legend.

**Reasoning**:
To visualize the distribution of heart disease outcomes as requested in the subtask, I will use `seaborn.countplot` on the target variable `y`, and then set appropriate labels and a title for the plot.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Create a count plot for the target variable 'y'
plt.figure(figsize=(8, 6))
sns.countplot(x=y['num'], palette='viridis')
plt.title('Distribution of Heart Disease Outcomes')
plt.xlabel('Heart Disease Status (0 = No Disease, 1-4 = Various Stages of Disease)')
plt.ylabel('Count')
plt.xticks(ticks=[0, 1, 2, 3, 4], labels=['No Disease', 'Stage 1', 'Stage 2', 'Stage 3', 'Stage 4'])
plt.show()

"""**Reasoning**:
The previous `countplot` call generated a `FutureWarning` regarding the use of `palette` without `hue`. To fix this, I will assign the `x` variable to `hue` and set `legend=False` as suggested by the warning, ensuring the plot's functionality remains the same while addressing the deprecation notice.


"""

import matplotlib.pyplot as plt
import seaborn as sns

# Create a count plot for the target variable 'y'
plt.figure(figsize=(8, 6))
sns.countplot(x=y['num'], hue=y['num'], palette='viridis', legend=False)
plt.title('Distribution of Heart Disease Outcomes')
plt.xlabel('Heart Disease Status (0 = No Disease, 1-4 = Various Stages of Disease)')
plt.ylabel('Count')
plt.xticks(ticks=[0, 1, 2, 3, 4], labels=['No Disease', 'Stage 1', 'Stage 2', 'Stage 3', 'Stage 4'])
plt.show()

"""**Reasoning**:
To understand the relationships between numerical features and the target variable, I will create a correlation heatmap by first concatenating the features and target, calculating the correlation matrix, and then visualizing it using `seaborn.heatmap`.


"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Combine features (X) and target (y) for correlation calculation
df_combined = pd.concat([X, y], axis=1)

# Calculate the correlation matrix
correlation_matrix = df_combined.corr()

# Plot the heatmap
plt.figure(figsize=(12, 10))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation Heatmap of Numerical Features and Target')
plt.show()

"""## Summary of Key Insights from Visualizations

### Histograms of Features (X)
*   **Age:** The distribution of age appears somewhat normal, with a peak around 50-60 years, indicating that most patients in the dataset fall within this age range.
*   **trestbps (resting blood pressure):** The distribution is skewed slightly to the right, with most values clustering between 120 and 140 mmHg. Some outliers exist at higher blood pressure readings.
*   **chol (serum cholestoral):** This feature also shows a right-skewed distribution, with the majority of patients having cholesterol levels between 200 and 300 mg/dl. There are a few individuals with very high cholesterol.
*   **thalach (maximum heart rate achieved):** The distribution is fairly symmetrical, centered around 150-160 bpm, suggesting a typical range of maximum heart rates in the patient group.
*   **oldpeak (ST depression induced by exercise relative to rest):** This feature is heavily skewed to the right, with many patients having low or zero ST depression, and fewer patients showing higher values. This could indicate that significant ST depression is less common.
*   **ca (number of major vessels colored by flourosopy):** The distribution is concentrated at 0, indicating a large number of patients have no major vessels colored, followed by a decreasing count for 1, 2, and 3 vessels. This suggests that severe blockages are less common.
*   **thal:** The most frequent value is 3 (normal), followed by 7 (reversible defect), and 6 (fixed defect), indicating varying degrees of thalassemia presence.

### Bar Plot of Target Variable (y)
*   The target variable `num` (diagnosis of heart disease) shows that the majority of patients (164 out of 303) have no heart disease (value 0). The number of patients decreases significantly with increasing stages of heart disease (1-4). This imbalance in the target variable should be considered in any predictive modeling.

### Correlation Heatmap
*   **Positive Correlations with 'num' (Heart Disease):**
    *   `cp` (chest pain type): Higher values of chest pain type (especially atypical or non-anginal pain, or asymptomatic) show a positive correlation with heart disease. Values 1-4 for `cp` are not ordered in severity, so the correlation might be complex.
    *   `exang` (exercise induced angina): Patients with exercise-induced angina are positively correlated with heart disease.
    *   `oldpeak` (ST depression): A higher ST depression is positively correlated with heart disease.
    *   `ca` (number of major vessels): An increase in the number of major vessels colored by fluoroscopy is positively correlated with heart disease.
    *   `thal`: Higher values of thal (indicating fixed or reversible defects rather than normal) are positively correlated with heart disease.
*   **Negative Correlations with 'num' (Heart Disease):**
    *   `thalach` (maximum heart rate achieved): A higher maximum heart rate achieved is negatively correlated with heart disease, suggesting that healthier hearts can achieve higher rates.
*   **Other Notable Correlations:**
    *   `age` shows a moderate positive correlation with `trestbps`, `chol`, and `oldpeak`, which is expected as these conditions often worsen with age.
    *   `sex` shows some correlation with `trestbps` and `chol`, and a notable negative correlation with `thalach` (males tend to have higher resting blood pressure and cholesterol, and lower max heart rate).
    *   `cp` (chest pain type) is moderately correlated with `exang` and `oldpeak`, which makes sense as certain chest pain types might be associated with exercise-induced angina and ST depression.

## Summary:

### Data Analysis Key Findings

*   **Dataset Overview**: The Heart Disease dataset contains 303 instances (patients) and 13 features, with one target variable (`num`).
*   **Missing Values**: Features `ca` (number of major vessels colored by fluoroscopy) and `thal` (thalassemia) contain a small number of missing values (4 for `ca`, 2 for `thal`).
*   **Feature Distributions**:
    *   `Age` is somewhat normally distributed, peaking between 50-60 years.
    *   `trestbps` (resting blood pressure) and `chol` (serum cholesterol) are right-skewed, with most values between 120-140 mmHg and 200-300 mg/dl, respectively.
    *   `thalach` (maximum heart rate achieved) is fairly symmetrical, centered around 150-160 bpm.
    *   `oldpeak` (ST depression), `ca`, and `thal` are heavily skewed towards lower values, indicating that many patients have little to no ST depression, no major vessels colored, or normal thalassemia (`thal` value 3).
*   **Target Variable Imbalance**: The target variable `num` (heart disease diagnosis) shows a significant class imbalance. The majority of patients (164 out of 303) are diagnosed with no heart disease (`num=0`), while the counts for various stages of heart disease (1-4) are considerably lower (55, 36, 35, and 13 respectively).
*   **Key Correlations with Heart Disease (`num`):**
    *   **Positive Correlations**: `cp` (chest pain type), `exang` (exercise-induced angina), `oldpeak` (ST depression), `ca` (number of major vessels), and `thal` (thalassemia) show positive correlations with the presence and severity of heart disease.
    *   **Negative Correlation**: `thalach` (maximum heart rate achieved) is negatively correlated with heart disease, suggesting that patients with higher maximum heart rates are less likely to have heart disease.

### Insights or Next Steps

*   **Address Data Imbalance**: The significant class imbalance in the target variable warrants consideration. Techniques like oversampling, undersampling, or using algorithms robust to imbalance should be explored during model building.
*   **Handle Missing Values**: Imputation strategies should be applied to the `ca` and `thal` features to handle the missing values before any predictive modeling.
"""